spring.application.name=GuestHouse-Booking-System
spring.profiles.active=local
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false