server.port=8080
spring.datasource.url=jdbc:mysql://booking-db:3306/guesthousebooking?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
customer.service.url=http://customer-service:8081/